# Generated by Django 4.2.3 on 2024-03-02 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='home_feedback',
            new_name='Home_feedbacks',
        ),
    ]
